### ISSUE TITLE
希望能增加忽略jar包配置，使用中有遇到包重复问题

### ISSUE THREAD

**Issue by loseleo** [cpdroid/fat-aar#2]
Duplicate class androidx.versionedparcelable.ParcelField found in modules classes.jar (com.android.support:versionedparcelable:28.0.0) and versionedparcelable.jar 

目前改了源码使用中

**Comment by cpdroid** [comment]
@loseleo  这是没有忽略androidx开头的包导致的，先更新到1.0.2，会自动忽略androidx开头的包。
忽略jar包配置在开发中，很快就会发出来

**Comment by cpdroid** [comment]
1.1.0版本已经发布，现在可以自定义忽略依赖了，详情见README
