### ISSUE TITLE
com.google 应该可以添加忽略

### ISSUE THREAD

**Issue by daxiong--** [cpdroid/fat-aar#4]

**Comment by daxiong--** [comment]
或者开放自定义忽略？

**Comment by daxiong--** [comment]
Execution failed for task ':library:baselibrary:mergeDebugResources'.
> [dimen/design_appbar_elevation] /Users/arthur/Desktop/code/eros/StoreWeex/platforms/android/WeexFrameworkWrapper/library/baselibrary/src/main/res/values/dimens.xml	[dimen/design_appbar_elevation] /Users/arthur/Desktop/code/eros/StoreWeex/platforms/android/WeexFrameworkWrapper/library/baselibrary/build/aar_plugin/exploded_aar/com.google.android.material/material/1.0.0/res/values/values.xml: Error: Duplicate resources

**Comment by cpdroid** [comment]
@daxiong-- 自定义忽略包正在开发中，上面这个问题是资源冲突，或许可以考虑将 */src/main/res/values/dimens.xml* 目录下的的 *design_appbar_elevation* 属性换个名字，比如加个模块前缀.

**Comment by daxiong--** [comment]
666

**Comment by cpdroid** [comment]
1.1.0版本已经发布，现在可以自定义忽略依赖了，详情见README

**Comment by daxiong--** [comment]
老哥，6的飞起!
