### ISSUE TITLE
  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder

### ISSUE THREAD

**Issue by EiuaLee** [cpdroid/fat-aar#9]
libaray开启混淆的情况下报类似于上面的错误，不开混淆没问题。
以下为打包日志
 jar info: converter-gson converter-gson.jar (com.squareup.retrofit2:converter-gson:2.3.0) null com.squareup.retrofit2
   jar info: adapter-rxjava2 adapter-rxjava2.jar (com.squareup.retrofit2:adapter-rxjava2:2.3.0) null com.squareup.retrofit2
   jar info: retrofit retrofit.jar (com.squareup.retrofit2:retrofit:2.3.0) null com.squareup.retrofit2
   jar info: gson gson.jar (com.google.code.gson:gson:2.7) null com.google.code.gson
   AAR:rxandroid.aar (io.reactivex.rxjava2:rxandroid:2.1.1) pkgName: io.reactivex.android
   jar info: rxjava rxjava.jar (io.reactivex.rxjava2:rxjava:2.2.13) null io.reactivex.rxjava2
   jar info: logging-interceptor logging-interceptor.jar (com.squareup.okhttp3:logging-interceptor:3.4.1) null com.squareup.okhttp3
   jar info: wechat-sdk-android-without-mta wechat-sdk-android-without-mta.jar (com.tencent.mm.opensdk:wechat-sdk-android-without-mta:5.5.7) null com.tencent.mm.opensdk
   jar info: okhttp okhttp.jar (com.squareup.okhttp3:okhttp:3.8.0) null com.squareup.okhttp3
   jar info: reactive-streams reactive-streams.jar (org.reactivestreams:reactive-streams:1.0.3) null org.reactivestreams
   jar info: okio okio.jar (com.squareup.okio:okio:1.13.0) null com.squareup.okio

**Comment by cpdroid** [comment]
@EiuaLee 能给个demo或者简要说下工程结构吗，我复现下

**Comment by EiuaLee** [comment]
没事了，需要在defaultConfig 添加
 consumerProguardFiles 'proguard-rules.pro' 
把混淆的文件打入aar里面才行
